### PR TITLE
It adds a solution to the second task

### PR DESCRIPTION
**Pull request by masontikhonov**
# Links to check:

## Serverless deployment
* CloudFront: [https://d296a7hkdlq6od.cloudfront.net/](https://d296a7hkdlq6od.cloudfront.net/)
* S3 Static Site: [http://node-aws-shop-react.s3-website-eu-west-1.amazonaws.com/](http://node-aws-shop-react.s3-website-eu-west-1.amazonaws.com/)

## Manual deployment
* CloudFront: [https://d27a3n1oozoscp.cloudfront.net/](https://d27a3n1oozoscp.cloudfront.net/)
* S3 Static Site: [http://node-aws-shop-react-manual.s3-website-eu-west-1.amazonaws.com/](http://node-aws-shop-react-manual.s3-website-eu-west-1.amazonaws.com/)

When deploying on your own, pay attention to the `provider -> profile` field in the `serverless.yml` file.

### CODE REVIEW

**Comment by damirel** [comment]
@masontikhonov Please add links with manual deploy

**Comment by masontikhonov** [comment]
> Please add links with manual deploy
@damirel,
This is impossible, since the task directly instructs to destroy the manual deployment.
See Section 2.2.2.: "Destroy created AWS infrastructure (S3 bucket and CloudFront distribution) from the previous part and steps. Make sure nothing is left"

**Comment by damirel** [comment]
@masontikhonov The description is incorrect. You can read discussion in discord. So please add the links

**Comment by masontikhonov** [comment]
@damirel Could you check again?

**Pull request merged**
